[0m08:45:14.609139 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002767B7B21C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002767E1C9790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002767E1C92E0>]}


============================== 08:45:14.638241 | 7344e82d-4c03-46eb-ab44-cc183d162a79 ==============================
[0m08:45:14.638241 [info ] [MainThread]: Running with dbt=1.7.9
[0m08:45:14.640247 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\PC\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m08:48:37.339840 [debug] [MainThread]: Starter project path: c:\users\pc\appdata\local\programs\python\python39\lib\site-packages\dbt\include\starter_project
[0m08:48:37.500397 [info ] [MainThread]: 
Your new dbt project "WeatherModels" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m08:48:37.505080 [info ] [MainThread]: Setting up your profile.
[0m08:51:59.524079 [info ] [MainThread]: Profile WeatherModels written to C:\Users\PC\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m08:51:59.529082 [debug] [MainThread]: Command `dbt init` succeeded at 08:51:59.529082 after 405.05 seconds
[0m08:51:59.531084 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002767B7B21C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002767E1C9DF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002767E2C6160>]}
[0m08:51:59.532082 [debug] [MainThread]: Flushing usage events
[0m08:52:55.932390 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000230DB34F370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000230DDD5F400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000230DDD5FC40>]}


============================== 08:52:55.939703 | d77425a8-6a12-4233-857f-4522729d389d ==============================
[0m08:52:55.939703 [info ] [MainThread]: Running with dbt=1.7.9
[0m08:52:55.941712 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\PC\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m08:52:55.942712 [info ] [MainThread]: dbt version: 1.7.9
[0m08:52:55.944705 [info ] [MainThread]: python version: 3.9.0
[0m08:52:55.946705 [info ] [MainThread]: python path: c:\users\pc\appdata\local\programs\python\python39\python.exe
[0m08:52:55.949709 [info ] [MainThread]: os info: Windows-10-10.0.19041-SP0
[0m08:52:55.974714 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.bigquery'
[0m08:52:56.176707 [info ] [MainThread]: Using profiles dir at C:\Users\PC\.dbt
[0m08:52:56.178705 [info ] [MainThread]: Using profiles.yml file at C:\Users\PC\.dbt\profiles.yml
[0m08:52:56.180709 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\PC\Downloads\DataPipelineProject\dbt_project.yml
[0m08:52:56.182710 [info ] [MainThread]: Configuration:
[0m08:52:56.184922 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m08:52:56.186917 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m08:52:56.189917 [info ] [MainThread]: Required dependencies:
[0m08:52:56.191917 [debug] [MainThread]: Executing "git --help"
[0m08:52:56.326914 [debug] [MainThread]: STDOUT: "b"usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m08:52:56.327911 [debug] [MainThread]: STDERR: "b''"
[0m08:52:56.328910 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m08:52:56.351920 [info ] [MainThread]: Connection test skipped since no profile was found
[0m08:52:56.352905 [info ] [MainThread]: [31m2 checks failed:[0m
[0m08:52:56.356931 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "PROJET1", target "dev" invalid: Runtime Error
    Could not find adapter type bigquery!


[0m08:52:56.361927 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\PC\Downloads\DataPipelineProject\dbt_project.yml> not found

[0m08:52:56.369947 [debug] [MainThread]: Command `dbt debug` failed at 08:52:56.368927 after 0.54 seconds
[0m08:52:56.371926 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000230DB34F370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000230DDD64EB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000230DDECDBB0>]}
[0m08:52:56.373924 [debug] [MainThread]: Flushing usage events
[0m13:10:20.840716 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027A666BD940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027A690C1A60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027A690C13D0>]}


============================== 13:10:20.871970 | eefff3a1-693a-42ff-8581-7b34fd0cd4cc ==============================
[0m13:10:20.871970 [info ] [MainThread]: Running with dbt=1.7.9
[0m13:10:20.871970 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\PC\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run --select Level1_models', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:10:20.871970 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\PC\Downloads\DataPipelineProject\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:10:20.882919 [debug] [MainThread]: Command `dbt run` failed at 13:10:20.882919 after 0.14 seconds
[0m13:10:20.884915 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027A666BD940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027A690B0430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027A690C1520>]}
[0m13:10:20.886915 [debug] [MainThread]: Flushing usage events
